<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Feature_MM" nsURI="https://fr.wikipedia.org/wiki/Feature_model">
  <eClassifiers xsi:type="ecore:EClass" name="Feature_model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Root"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubFeatures" upperBound="-1"
        eType="#//Feature" containment="true" eOpposite="#//Feature/parent_name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent_name" eType="#//Feature"
        eOpposite="#//Feature/SubFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alternative" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" lowerBound="2"
        upperBound="-1" eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="F_From" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="F_to" lowerBound="1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean_Constraint" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Implies" eSuperTypes="#//Boolean_Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exclude" eSuperTypes="#//Boolean_Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusive" eSuperTypes="#//Alternative"/>
</ecore:EPackage>
