<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="JavaBIP_MM" nsURI="https://www.bliudze.me/simon/2021/01/compounds/">
  <eClassifiers xsi:type="ecore:EClass" name="Java_BIP_project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector_motifs" upperBound="-1"
        eType="#//Connector_Motif" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states_link_to_State_Base"
        upperBound="-1" eType="#//State_Base" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial_s" lowerBound="1"
        eType="#//Initial_State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" lowerBound="1"
        upperBound="-1" eType="#//Transition_Base" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usableComponent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guards" upperBound="-1"
        eType="#//Guard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correspondsTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State_Base">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition_Base">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transition_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//State_Base"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dst" lowerBound="1" eType="#//State_Base"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Internal" eSuperTypes="#//Transition_Base"/>
  <eClassifiers xsi:type="ecore:EClass" name="Spontaneous" eSuperTypes="#//Transition_Base"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enforceable" eSuperTypes="#//Transition_Base">
    <eStructuralFeatures xsi:type="ecore:EReference" name="in_connector_end" lowerBound="1"
        upperBound="-1" eType="#//Connector_Motif_End" eOpposite="#//Connector_Motif_End/one_enforceable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initial_State" eSuperTypes="#//State_Base"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connector_Motif">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ends" lowerBound="1" upperBound="-1"
        eType="#//Connector_Motif_End" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connector_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector_Motif_End">
    <eStructuralFeatures xsi:type="ecore:EReference" name="one_enforceable" lowerBound="1"
        eType="#//Enforceable" eOpposite="#//Enforceable/in_connector_end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synchron" eSuperTypes="#//Connector_Motif_End">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" eSuperTypes="#//Connector_Motif_End">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
</ecore:EPackage>
